---
- name: 'Reload systemd'
  ansible.builtin.systemd:
    daemon_reload: true

- name: 'Restart slurm-exporter'
  ansible.builtin.systemd:
    name: 'slurm-exporter'
    state: 'restarted'

- name: 'Reload prometheus'
  ansible.builtin.systemd:
    name: 'prometheus'
    state: 'reloaded'
  delegate_to: 'allyrion'