---
# Configure systemd services for distributed-llama

- name: 'Create worker service configuration.'
  ansible.builtin.template:
    src: 'dllama-worker.service.j2'
    dest: '/etc/systemd/system/dllama-worker.service'
    mode: '0644'
  become: true
  when: distributed_llama.enable_worker
  notify: 'Restart dllama-worker service.'

- name: 'Create root node service configuration.'
  ansible.builtin.template:
    src: 'dllama-root.service.j2'
    dest: '/etc/systemd/system/dllama-root.service'
    mode: '0644'
  become: true
  when: distributed_llama.enable_root
  notify: 'Restart dllama-root service.'

- name: 'Create API server service configuration.'
  ansible.builtin.template:
    src: 'dllama-api.service.j2'
    dest: '/etc/systemd/system/dllama-api.service'
    mode: '0644'
  become: true
  when: 
    - distributed_llama.enable_api
    - distributed_llama.enable_root
  notify: 'Restart dllama-api service.'

- name: 'Create startup script for worker nodes.'
  ansible.builtin.template:
    src: 'start-dllama-worker.sh.j2'
    dest: "{{ distributed_llama.install_dir }}/bin/start-dllama-worker.sh"
    mode: '0755'
    owner: "{{ distributed_llama.user }}"
    group: "{{ distributed_llama.group }}"
  become: true
  when: distributed_llama.enable_worker

- name: 'Create startup script for root node.'
  ansible.builtin.template:
    src: 'start-dllama-root.sh.j2'
    dest: "{{ distributed_llama.install_dir }}/bin/start-dllama-root.sh"
    mode: '0755'
    owner: "{{ distributed_llama.user }}"
    group: "{{ distributed_llama.group }}"
  become: true
  when: distributed_llama.enable_root

- name: 'Reload systemd daemon.'
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: 'Enable and start worker service.'
  ansible.builtin.systemd_service:
    name: 'dllama-worker'
    enabled: true
    state: 'started'
  become: true
  when: distributed_llama.enable_worker

- name: 'Enable and start root service.'
  ansible.builtin.systemd_service:
    name: 'dllama-root'
    enabled: false  # Don't auto-start until models are available
    state: 'stopped'
  become: true
  when: distributed_llama.enable_root

- name: 'Enable and start API service.'
  ansible.builtin.systemd_service:
    name: 'dllama-api'
    enabled: false  # Don't auto-start until models are available
    state: 'stopped'
  become: true
  when: 
    - distributed_llama.enable_api
    - distributed_llama.enable_root