---
# Register distributed-llama services with Consul service registry

- name: Register distributed-llama worker with Consul
  template:
    src: consul-dllama-worker.json.j2
    dest: /etc/consul.d/dllama-worker.json
    mode: '0644'
  become: yes
  when: distributed_llama.enable_worker
  notify: reload consul

- name: Register distributed-llama root with Consul  
  template:
    src: consul-dllama-root.json.j2
    dest: /etc/consul.d/dllama-root.json
    mode: '0644'
  become: yes
  when: distributed_llama.enable_root
  notify: reload consul

- name: Register distributed-llama API with Consul
  template:
    src: consul-dllama-api.json.j2
    dest: /etc/consul.d/dllama-api.json
    mode: '0644'
  become: yes
  when:
    - distributed_llama.enable_api
    - distributed_llama.enable_root
  notify: reload consul

- name: Reload Consul configuration
  systemd:
    name: consul
    state: reloaded
  become: yes
  when: "'consul' in ansible_facts.services"