---
- name: 'Create "GitOps Repo" project.'
  kubernetes.core.k8s:
    state: 'present'
    definition:
      apiVersion: 'argoproj.io/v1alpha1'
      kind: 'AppProject'
      metadata:
        name: 'gitops-repo'
        # Argo CD resources need to deploy into the Argo CD namespace.
        namespace: 'argocd'
        finalizers:
          - 'resources-finalizer.argocd.argoproj.io'
      spec:
        description: 'GoldenTooth GitOps-Repo project'
        # Allow manifests to deploy from any Git repository.
        # This is an acceptable security risk because this is a lab environment
        # and I am the only user.
        sourceRepos:
          - '*'
        destinations:
          # Prevent any resources from deploying into the kube-system namespace.
          - namespace: '!kube-system'
            server: '*'
          # Allow resources to deploy into any other namespace.
          - namespace: '*'
            server: '*'
        clusterResourceWhitelist:
          # Allow any cluster resources to deploy.
          - group: '*'
            kind: '*'
  run_once: true
