---
- name: 'Setup Local Modifications to Bash Prompt'
  block:

    - name: 'Set up bash prompt system-wide.'
      ansible.builtin.template:
        src: 'bash-prompt-env.sh.j2'
        dest: '/etc/profile.d/bash-prompt-env.sh'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Copy Bash prompt injection script system-wide.'
      ansible.builtin.copy:
        src: "{{ role_path }}/files/bash_prompt.sh"
        dest: '/etc/bash_prompt.sh'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Copy Bash prompt template script system-wide.'
      ansible.builtin.template:
        src: "{{ role_path }}/templates/bash_prompt_local.sh.j2"
        dest: '/etc/bash_prompt_local.sh'
        owner: 'root'
        group: 'root'
        mode: '0644'
