---
- name: 'Create Consul Certificate Authority.'
  block:

    - name: 'Create temporary certificate directory.'
      ansible.builtin.tempfile:
        state: 'directory'
      register: 'temp_cert_dir'

    - name: 'Generate the Consul Certificate Authority.'
      ansible.builtin.shell:
        cmd: |
          consul tls ca create \
            -domain={{ consul_domain }}
        chdir: "{{ temp_cert_dir.path }}"

    - name: 'Slurp the CA cert.'
      ansible.builtin.slurp:
        src: "{{ temp_cert_dir.path }}/{{ consul_agent_ca_path | basename }}"
      register: 'consul_agent_ca_file_base64'

    - name: 'Slurp the CA key.'
      ansible.builtin.slurp:
        src: "{{ temp_cert_dir.path }}/{{ consul_agent_ca_key_path | basename }}"
      register: 'consul_agent_ca_key_file_base64'

  when: "inventory_hostname in groups['consul_server']"
  run_once: true

- name: 'Copy CA private key to servers only.'
  ansible.builtin.copy:
    content: "{{ consul_agent_ca_key_file_base64['content'] | b64decode }}"
    dest: "{{ consul_agent_ca_key_path }}"
    owner: 'consul'
    group: 'consul'
    mode: '0600'
  when: "inventory_hostname in groups['consul_server']"

- name: 'Copy CA certificate to all nodes.'
  ansible.builtin.copy:
    content: "{{ consul_agent_ca_file_base64['content'] | b64decode }}"
    dest: "{{ consul_agent_ca_path }}"
    owner: 'consul'
    group: 'consul'
    mode: '0600'
