
---
- name: 'Create temporary certificate directory.'
  ansible.builtin.tempfile:
    state: 'directory'
  register: 'temp_cert_dir'

- name: 'Generate the Consul server certificate.'
  ansible.builtin.shell:
    cmd: |
      consul tls cert create \
        -server \
        -additional-dnsname={{ clean_hostname }} \
        -additional-ipaddress={{ ipv4_address }} \
        -ca={{ consul_agent_ca_path }} \
        -dc={{ consul_datacenter }} \
        -domain={{ consul_domain }} \
        -key={{ consul_agent_ca_key_path }} \
        -node={{ clean_hostname }}
    chdir: "{{ temp_cert_dir.path }}"

- name: 'Copy certificates into place.'
  ansible.builtin.copy:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    remote_src: true
    owner: 'consul'
    group: 'consul'
    mode: '0600'
  loop:
    - src: "{{ temp_cert_dir.path }}/{{ consul_agent_server_path | basename }}"
      dest: "{{ consul_agent_server_path }}"
    - src: "{{ temp_cert_dir.path }}/{{ consul_agent_server_key_path | basename }}"
      dest: "{{ consul_agent_server_key_path }}"
  loop_control:
    loop_var: 'file'
  no_log: true
