---
- name: 'Generate Consul server certificate using step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca.executable }} \
        ca certificate \
        "{{ clean_hostname }}.server.{{ consul.datacenter }}.{{ consul.domain }}" \
        "{{ consul.cert_path }}" \
        "{{ consul.key_path }}" \
        --provisioner="{{ step_ca.provisioner }}" \
        --password-file="{{ step_ca.provisioner_password_path }}" \
        --san="{{ clean_hostname }}" \
        --san="{{ clean_hostname }}.server.{{ consul.datacenter }}.{{ consul.domain }}" \
        --san="server.{{ consul.datacenter }}.{{ consul.domain }}" \
        --san="{{ ipv4_address }}" \
        --not-after="24h" \
        --console \
        --force
  notify:
    - 'Restart Consul service.'

- name: 'Repair permissions on Consul certs directory.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'file'
    owner: 'consul'
    group: 'consul'
    mode: '0600'
  loop:
    - "{{ consul.key_path }}"
    - "{{ consul.cert_path }}"
  loop_control:
    loop_var: 'item'
