---
- name: 'Ensure Consul certs directory exists.'
  ansible.builtin.file:
    path: "{{ consul_certs_path }}"
    state: 'directory'
    owner: 'consul'
    group: 'consul'
    mode: '0700'

- name: 'Create Certificate Authority.'
  ansible.builtin.include_tasks: 'create_ca.yaml'

- name: 'Create Server certificates.'
  ansible.builtin.include_tasks: 'create_server_certs.yaml'
  when: "inventory_hostname in groups['consul_server']"
