---
- name: 'Install Grafana.'
  ansible.builtin.apt:
    pkg:
      - 'grafana'
    state: 'present'
  notify:
    - 'Restart Grafana service.'

- name: 'Configure Grafana.'
  ansible.builtin.template:
    src: 'grafana.ini.j2'
    dest: '/etc/grafana/grafana.ini'
    owner: 'grafana'
    group: 'grafana'
    mode: '0600'
  notify:
    - 'Restart Grafana service.'
