---
- name: 'Reload Systemd.'
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: 'Restart Blackbox Exporter.'
  ansible.builtin.systemd_service:
    name: 'blackbox-exporter'
    state: 'restarted'

- name: 'Restart Prometheus.'
  ansible.builtin.systemd_service:
    name: 'prometheus'
    state: 'restarted'
  delegate_to: "{{ groups['prometheus'] | first }}"

- name: 'Restart Nginx on the load balancer.'
  ansible.builtin.systemd_service:
    name: 'nginx'
    state: 'restarted'
  delegate_to: "{{ groups['haproxy'] | first }}"