---
- name: Test Prometheus Only
  hosts: prometheus
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Initialize test variables
      set_fact:
        test_results: []
        service_health: {}
        certificate_status: []

    - name: Test Prometheus core functionality
      include_role:
        name: goldentooth.test_prometheus

    - name: Test Prometheus scraping
      include_role:
        name: goldentooth.test_prometheus_scraping

    - name: Test Prometheus alerting
      include_role:
        name: goldentooth.test_prometheus_alerts

    - name: Show results
      debug:
        msg: |
          Prometheus Test Results:
          - Core: {{ service_health.prometheus | default('not tested') }}
          - Scraping: {{ service_health.prometheus_scraping | default('not tested') }}
          - Alerts: {{ service_health.prometheus_alerts | default('not tested') }}
          - Total tests: {{ test_results | length }}
          - Passed: {{ test_results | selectattr('success', 'equalto', true) | list | length }}
          - Failed: {{ test_results | selectattr('success', 'equalto', false) | list | length }}