---
# Handlers for goldentooth.setup_mcp_server role

- name: 'Restart goldentooth-mcp.'
  ansible.builtin.systemd_service:
    name: "{{ mcp_server_service_name }}"
    state: restarted
    daemon_reload: true
  become: true

- name: 'Reload systemd.'
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: 'Start goldentooth-mcp.'
  ansible.builtin.systemd_service:
    name: "{{ mcp_server_service_name }}"
    state: started
    enabled: true
  become: true

- name: 'Reload Consul configuration.'
  ansible.builtin.systemd_service:
    name: 'consul'
    state: 'reloaded'