---
- name: 'Select editor.'
  ansible.builtin.lineinfile:
    path: '~/.selected_editor'
    regexp: '^SELECTED_EDITOR'
    line: "SELECTED_EDITOR={{ my.editor }}"
    create: true
    state: 'present'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: 'Install uv (includes uvx).'
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/install-uv.sh
    mode: '0755'
  register: download_uv

- name: 'Run uv installer.'
  ansible.builtin.shell: /tmp/install-uv.sh
  when: download_uv.changed

- name: 'Create ~/.bash_local with uvx setup.'
  ansible.builtin.template:
    src: 'goldentooth-user-env.sh.j2'
    dest: '/etc/profile.d/goldentooth-user-env.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'

# Note: User environment now configured system-wide in /etc/profile.d/
