---
# Description: Install and configure Claude Code CLI on cluster nodes

- name: 'Verify Node.js and NPM are installed'
  ansible.builtin.command: "{{ item }} --version"
  register: version_check
  changed_when: false
  loop:
    - node
    - npm

- name: 'Display Node.js and NPM versions'
  ansible.builtin.debug:
    msg: "Node.js and NPM are available: {{ version_check.results | map(attribute='stdout') | join(' and ') }}"

- name: 'Test Claude Code CLI availability via NPX'
  ansible.builtin.command: npx --yes @anthropic-ai/claude-code --version
  register: claude_code_test
  changed_when: false
  failed_when: false

- name: 'Display Claude Code CLI test result'
  ansible.builtin.debug:
    msg: "Claude Code CLI test: {{ claude_code_test.stdout if claude_code_test.rc == 0 else 'Not accessible or network issue' }}"

- name: 'Create Claude Code environment configuration'
  ansible.builtin.template:
    src: claude-code-env.sh.j2
    dest: /etc/profile.d/claude-code-env.sh
    mode: '0644'
    owner: root
    group: root
  notify: 'reload shell environment'

- name: 'Create Claude wrapper script'
  ansible.builtin.copy:
    dest: /usr/local/bin/claude
    mode: '0755'
    owner: root
    group: root
    content: |
      #!/bin/bash
      # Claude Code CLI wrapper script  
      # Generated by Ansible goldentooth.setup_claude_code role

      exec npx --yes @anthropic-ai/claude-code "$@"
  notify: 'reload shell environment'

- name: 'Create claude-code wrapper script for compatibility'
  ansible.builtin.copy:
    dest: /usr/local/bin/claude-code
    mode: '0755'
    owner: root
    group: root
    content: |
      #!/bin/bash
      # Claude Code CLI wrapper script (compatibility)
      # Generated by Ansible goldentooth.setup_claude_code role

      exec npx --yes @anthropic-ai/claude-code "$@"
  notify: 'reload shell environment'

- name: 'Remove any existing cc Claude wrapper (conflicts with C compiler)'
  ansible.builtin.file:
    path: /usr/local/bin/cc
    state: absent
  notify: 'reload shell environment'

- name: 'Verify Claude installation'
  ansible.builtin.command: /usr/local/bin/claude --version
  register: claude_version_check
  changed_when: false
  failed_when: false

- name: 'Display installation result'
  ansible.builtin.debug:
    msg: |
      Claude CLI setup complete on {{ inventory_hostname }}
      {% if claude_version_check.rc == 0 %}
      Version: {{ claude_version_check.stdout }}
      Available commands: claude, claude-code
      {% else %}
      Note: Version check failed - may require network access for first run
      Commands available: claude, claude-code (will download on first use)
      {% endif %}

- name: 'Verify C compiler is still available'
  ansible.builtin.command: cc --version
  register: c_compiler_test
  changed_when: false
  failed_when: false

- name: 'Confirm C compiler not broken'
  ansible.builtin.debug:
    msg: "C compiler 'cc' {{ 'still works correctly' if c_compiler_test.rc == 0 else 'may need to be installed' }}"