---
- name: 'Create "Incubator" project.'
  kubernetes.core.k8s:
    state: 'present'
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: incubator
        # Argo CD resources need to deploy into the Argo CD namespace.
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        description: GoldenTooth incubator project
        # Allow manifests to deploy from any Git repository.
        # This is an acceptable security risk because this is a lab environment.
        sourceRepos:
          - '*'
        destinations:
          # Prevent any resources from deploying into the kube-system namespace.
          - namespace: '!kube-system'
            server: '*'
          # Allow resources to deploy into any other namespace.
          - namespace: '*'
            server: '*'
        clusterResourceWhitelist:
          # Allow any cluster resources to deploy.
          - group: '*'
            kind: '*'
  run_once: true

- name: 'Create "Incubator" project.'
  kubernetes.core.k8s:
    state: 'present'
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: incubator
        namespace: argocd
        labels:
          name: incubator
          managed-by: argocd
      spec:
        project: incubator
        source:
          repoURL: "https://github.com/{{ cluster.name }}/incubator.git"
          path: './'
          targetRevision: HEAD
        destination:
          server: 'https://kubernetes.default.svc'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
  run_once: true
