clean_hostname: allyrion
mac_address: d8:3a:dd:8a:7d:aa
ipv4_address: 10.4.0.10
prompt:
  colors:
    primary: 124
    secondary: 220
    tertiary: 52
  emoji: ✋
host_index: 0

# #############################################################################
# Variables for vendored roles.
# #############################################################################

nfs_exports:
- "/mnt/usb1 *(rw,sync,no_root_squash,no_subtree_check)"

# MCP server configuration - use different port due to nginx conflicts
mcp_server_port: 8085
