---
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: "{{ pi_timezone }}"

- name: 'Set the keyboard.'
  ansible.builtin.lineinfile:
    path: '/etc/default/keyboard'
    regexp: '^XKBLAYOUT='
    line: 'XKBLAYOUT="{{ pi_keyboard }}"'
    state: 'present'
  become: yes
  register: 'set_keyboard'

- name: 'Enable fan control.'
  ansible.builtin.lineinfile:
    path: '/boot/config.txt'
    regexp: '^#?dtoverlay=gpio-fan'
    line: "dtoverlay=gpio-fan,gpiopin={{ pi_fan_gpio }},temp={{ pi_fan_temp }}"
    state: 'present'
  become: yes
  register: 'enable_fan'

- name: 'Enable overclocking.'
  ansible.builtin.lineinfile:
    path: '/boot/config.txt'
    regexp: "^#?{{ line.prefix }}"
    line: "{{ line.line }}"
    state: 'present'
  become: yes
  loop:
    - prefix: 'arm_boost'
      line: 'arm_boost=1'
    - prefix: 'arm_freq'
      line: 'arm_freq={{ pi_overclock_freq }}'
    - prefix: 'over_voltage'
      line: 'over_voltage={{ pi_overclock_voltage }}'
  loop_control:
    loop_var: 'line'
  register: 'enable_overclock'

- name: 'Disable swap.'
  when: 'ansible_swaptotal_mb > 0'
  block:
    - name: 'Disable the swapfile.'
      ansible.builtin.shell: 'dphys-swapfile swapoff'
      become: yes
      changed_when: no

    - name: 'Uninstall the swapfile.'
      ansible.builtin.shell: 'dphys-swapfile uninstall'
      become: yes
      changed_when: no

    - name: 'Disable the swapfile service.'
      ansible.builtin.systemd:
        name: 'dphys-swapfile'
        state: 'stopped'
        enabled: 'no'
      become: yes

    - name: 'Indicate that swap was disabled.'
      ansible.builtin.set_fact:
        disable_swap: true

- name: 'Create selected editor file if it does not exist.'
  ansible.builtin.file:
    path: '~/.selected_editor'
    state: 'file'

- name: 'Select editor.'
  ansible.builtin.lineinfile:
    path: '~/.selected_editor'
    regexp: '^SELECTED_EDITOR'
    line: 'SELECTED_EDITOR="/bin/nano"'
    state: 'present'

- name: 'Indicate reboot required.'
  ansible.builtin.set_fact:
    reboot_required: true
  when: 'set_keyboard.changed or enable_fan.changed or enable_overclock.changed or disable_swap | default(false)'

- name: 'Reboot.'
  ansible.builtin.reboot:
  become: yes
  when: 'reboot_required | default(false)'
