---
- name: 'Trigger systemd daemon-reload.'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart Loki service.'
  ansible.builtin.systemd_service:
    name: 'loki'
    state: 'restarted'

- name: 'Reload Consul configuration.'
  ansible.builtin.systemd_service:
    name: 'consul'
    state: 'reloaded'