---
- name: 'Ensure directory for Grafana certs exists.'
  ansible.builtin.file:
    path: "{{ grafana.certs_path }}"
    state: 'directory'
    owner: 'grafana'
    group: 'grafana'
    mode: '0755'

- name: 'Generate certificate for Grafana from step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca.executable }} \
        ca certificate \
        grafana.{{ cluster.services_domain }} \
        "{{ grafana.cert_path }}" \
        "{{ grafana.key_path }}" \
        --provisioner="{{ step_ca.default_provisioner.name }}" \
        --password-file="{{ step_ca.default_provisioner.password_path }}" \
        --san="grafana.{{ cluster.services_domain }}" \
        --san="grafana" \
        --san='localhost' \
        --san="{{ clean_hostname }}" \
        --san="{{ clean_hostname }}.{{ cluster.node_domain }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force
  notify:
    - 'Restart Grafana service.'

- name: 'Repair permissions on Grafana certs.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'file'
    owner: 'grafana'
    group: 'grafana'
    mode: '0600'
  loop:
    - "{{ grafana.cert_path }}"
    - "{{ grafana.key_path }}"
  loop_control:
    loop_var: 'item'
  notify:
    - 'Restart Grafana service.'
