# #############################################################################
# Variables for vendored roles.
# #############################################################################

# geerlingguy.containerd


# geerlingguy.kubernetes
kubernetes_role: 'control_plane'
