---
- name: 'Install packages needed to use the Kubernetes Apt repository.'
  ansible.builtin.apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg'
      - 'python3-debian'
      - 'python3-kubernetes'
    state: 'present'

- name: 'Add Kubernetes repository.'
  ansible.builtin.deb822_repository:
    name: 'kubernetes'
    types:
      - 'deb'
    uris:
      - "{{ k8s_apt_repo_url }}"
    suites:
      - '/'
    architectures:
      - 'arm64'
    signed_by: "{{ k8s_apt_repo_url }}/Release.key"
  notify: 'Update Apt cache.'

- name: 'Install Kubernetes packages.'
  ansible.builtin.apt:
    name: "{{ k8s_packages }}"
    state: 'present'
  notify:
    - 'Hold Kubernetes packages.'
    - 'Enable and restart kubelet service.'
