---
- name: 'Remove any existing gossip key.'
  ansible.builtin.file:
    path: "{{ consul.opt_path }}/serf/local.keyring"
    state: 'absent'

- name: 'Generate the gossip encryption key.'
  ansible.builtin.command:
    cmd: 'consul keygen'
  no_log: true
  run_once: true
  register: 'gossip_key'

- name: 'Setup Consul on server nodes.'
  block:

    - name: 'Set fact for the Consul agent token on server nodes.'
      ansible.builtin.set_fact:
        consul_agent_token: "{{ secret_vault.consul.mgmt_token }}"

    - name: 'Update configuration for server nodes.'
      ansible.builtin.include_tasks: 'update_config.yaml'

  when: "clean_hostname in groups['consul_server']"

- name: 'Setup Consul on client nodes.'
  block:

    - name: 'Create a Consul agent policy for each node.'
      community.general.consul_policy:
        host: "{{ consul.maybe_leader }}"
        scheme: 'http'
        port: 8500
        validate_certs: false
        token: "{{ secret_vault.consul.mgmt_token }}"
        ca_path: "{{ step_ca.ca_ref_cert_path }}"
        name: "{{ consul.agent_policy_name }}"
        description: "Consul agent policy for {{ clean_hostname }}"
        rules: "{{ lookup('ansible.builtin.template', 'consul.agent.policy.hcl.j2') }}"
      register: 'consul_policy'
      until: 'consul_policy is not failed'

    - name: 'Create Consul agent tokens.'
      community.general.consul_token:
        host: "{{ consul.maybe_leader }}"
        scheme: 'http'
        port: 8500
        validate_certs: false
        token: "{{ secret_vault.consul.mgmt_token }}"
        description: "Consul agent token"
        policies:
          - name: "{{ consul.agent_policy_name }}"
      register: 'consul_agent_token_object'
      until: 'consul_agent_token_object is not failed'

    - name: 'Set fact for the Consul agent token on client nodes.'
      ansible.builtin.set_fact:
        consul_agent_token: "{{ consul_agent_token_object.token.SecretID}}"

  when: "clean_hostname in groups['consul_client']"

- name: 'Update configuration for all nodes.'
  ansible.builtin.include_tasks: 'update_config.yaml'

- name: 'Set Consul environment variables in ~/.bashrc.'
  ansible.builtin.lineinfile:
    path: '~/.bashrc'
    regexp: "^export {{ variable.name }}"
    line: "export {{ variable.name }}={{ variable.value}}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - name: 'CONSUL_HTTP_ADDR'
      value: "http://{{ consul.maybe_leader }}:8500"
  loop_control:
    loop_var: 'variable'
