---
# Unified Consul setup role - handles ACL bootstrap, certificates, and configuration

- name: 'Bootstrap ACL system if needed (one-time operation).'
  ansible.builtin.include_tasks: 'bootstrap_acl.yaml'
  when: "clean_hostname in groups['consul_server']"
  run_once: true

- name: 'Ensure Consul certificates are role-appropriate.'
  ansible.builtin.include_tasks: 'manage_certificates.yaml'

- name: 'Setup Consul on server nodes.'
  block:

    - name: 'Set fact for the Consul agent token on server nodes.'
      ansible.builtin.set_fact:
        consul_agent_token: "{{ secret_vault.consul.mgmt_token }}"

    - name: 'Set fact for the Consul CLI token on server nodes (use mgmt token).'
      ansible.builtin.set_fact:
        consul_cli_token: "{{ secret_vault.consul.mgmt_token }}"

    - name: 'Update configuration for server nodes.'
      ansible.builtin.include_tasks: 'update_config.yaml'

  when: "clean_hostname in groups['consul_server']"

- name: 'Setup Consul on client nodes.'
  block:

    - name: 'Create a Consul agent policy for each node.'
      community.general.consul_policy:
        host: "{{ consul.maybe_leader }}"
        token: "{{ secret_vault.consul.mgmt_token }}"
        ca_path: "{{ step_ca.root_cert_path }}"
        name: "{{ consul.agent_policy_name }}"
        description: "Consul agent policy for {{ clean_hostname }}"
        rules: "{{ lookup('ansible.builtin.template', 'consul.agent.policy.hcl.j2') }}"
      register: 'consul_policy'
      delegate_to: "{{ consul.maybe_leader }}"
      until: 'consul_policy is not failed'

    - name: 'Create Consul agent tokens.'
      community.general.consul_token:
        host: "{{ consul.maybe_leader }}"
        token: "{{ secret_vault.consul.mgmt_token }}"
        description: "Consul agent token"
        policies:
          - name: "{{ consul.agent_policy_name }}"
      register: 'consul_agent_token_object'
      delegate_to: "{{ consul.maybe_leader }}"
      until: 'consul_agent_token_object is not failed'

    - name: 'Set fact for the Consul agent token on client nodes.'
      ansible.builtin.set_fact:
        consul_agent_token: "{{ consul_agent_token_object.token.SecretID}}"

    - name: 'Create CLI token for client nodes.'
      community.general.consul_token:
        host: "{{ consul.maybe_leader }}"
        token: "{{ secret_vault.consul.mgmt_token }}"
        description: "CLI token for {{ clean_hostname }}"
        policies:
          - name: "{{ consul.agent_policy_name }}"
      register: 'consul_cli_token_object'
      delegate_to: "{{ consul.maybe_leader }}"
      until: 'consul_cli_token_object is not failed'

    - name: 'Set fact for the Consul CLI token on client nodes.'
      ansible.builtin.set_fact:
        consul_cli_token: "{{ consul_cli_token_object.token.SecretID}}"

  when: "clean_hostname in groups['consul_client']"

- name: 'Update configuration for all nodes.'
  ansible.builtin.include_tasks: 'update_config.yaml'

- name: 'Set Consul environment variables system-wide.'
  ansible.builtin.template:
    src: 'consul-env.sh.j2'
    dest: '/etc/profile.d/consul-env.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'