---
- name: 'Copy Consul service configuration into place on all nodes.'
  ansible.builtin.template:
    src: 'consul.service.j2'
    dest: '/etc/systemd/system/consul.service'
    owner: 'consul'
    group: 'consul'
    mode: '0600'
  notify:
    - 'Trigger systemd daemon-reload.'
    - 'Restart Consul service.'

- name: 'Ensure Consul service directory exists.'
  ansible.builtin.file:
    path: '/etc/systemd/system/cert-renewer@consul.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Enable cert-renewer service for Consul.'
  ansible.builtin.systemd_service:
    name: 'cert-renewer@consul.timer'
    enabled: true
    state: 'started'
  notify:
    - 'Trigger systemd daemon-reload.'

- name: 'Copy Consul certificate renewer configuration into place on all nodes.'
  ansible.builtin.template:
    src: 'cert-renewer@consul.conf.j2'
    dest: '/etc/systemd/system/cert-renewer@consul.service.d/override.conf'
  notify:
    - 'Trigger systemd daemon-reload.'

- name: 'Flush handlers.'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Copy Consul configuration into place on all nodes.'
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    owner: 'consul'
    group: 'consul'
    mode: '0600'
  loop:
    - src: 'consul.env.j2'
      dest: "{{ consul.env_config_path }}"
    - src: 'consul.hcl.j2'
      dest: "{{ consul.hcl_config_path }}"
  loop_control:
    loop_var: 'file'
  notify:
    - 'Restart Consul service.'

- name: 'Validate Consul configuration.'
  ansible.builtin.command:
    cmd: "consul validate {{ consul.etc_path }}"
  changed_when: false

- name: 'Flush handlers.'
  ansible.builtin.meta: 'flush_handlers'
