---
# Handlers for distributed-llama services

- name: 'Restart distributed-llama services.'
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: 'restarted'
  become: true
  loop:
    - 'dllama-worker'
    - 'dllama-root'
    - 'dllama-api'
  when:
    - item == "dllama-worker" and distributed_llama.enable_worker
    - item == "dllama-root" and distributed_llama.enable_root
    - item == "dllama-api" and distributed_llama.enable_api and distributed_llama.enable_root
  ignore_errors: true

- name: 'Restart dllama-worker service.'
  ansible.builtin.systemd_service:
    name: 'dllama-worker'
    state: 'restarted'
  become: true
  when: distributed_llama.enable_worker

- name: 'Restart dllama-root service.'
  ansible.builtin.systemd_service:
    name: 'dllama-root'
    state: 'restarted'
  become: true
  when: distributed_llama.enable_root

- name: 'Restart dllama-api service.'
  ansible.builtin.systemd_service:
    name: 'dllama-api'
    state: 'restarted'
  become: true
  when:
    - distributed_llama.enable_api
    - distributed_llama.enable_root

- name: 'Reload Consul configuration.'
  ansible.builtin.systemd_service:
    name: 'consul'
    state: 'reloaded'
