---
- name: 'Set the node hostname.'
  ansible.builtin.hostname:
    name: "{{ clean_hostname }}"

- name: 'Add the hostname to /etc/hosts.'
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: "{{ ipv4_address }} {{ clean_hostname }}"
    state: 'present'
