---
- name: 'Install ACL support.'
  ansible.builtin.apt:
    pkg:
      - 'acl'
    state: 'present'

- name: 'Create web root directory.'
  ansible.builtin.file:
    path: "{{ node_homepage.web_root }}"
    state: 'directory'
    mode: '0755'
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"

- name: 'Sets default ACL for Nginx on web root directory.'
  ansible.posix.acl:
    path: "{{ node_homepage.web_root }}"
    entity: "{{ node_homepage.nginx.user }}"
    etype: 'user'
    permissions: 'rX'
    state: 'present'
    recursive: true
    default: true
  notify:
    - 'Restart Nginx.'

- name: 'Install nginx.'
  ansible.builtin.apt:
    pkg:
      - 'nginx'
    state: 'present'
  notify:
    - 'Restart Nginx.'

- name: 'Remove default Nginx server configuration.'
  ansible.builtin.file:
    dest: '/etc/nginx/sites-enabled/default'
    state: 'absent'
  notify:
    - 'Restart Nginx.'

- name: 'Configure Nginx.'
  ansible.builtin.template:
    src: 'node-homepage.conf.j2'
    dest: '/etc/nginx/sites-enabled/node-homepage.conf'
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"
    mode: '0644'
  notify:
    - 'Restart Nginx.'

- name: 'Copy index.html into place.'
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: "{{ node_homepage.web_root }}/index.html"
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"
    mode: '0755'

- name: 'Set the node 128x128 png.'
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ clean_hostname }}.png"
    dest: "{{ node_homepage.web_root }}/node.png"
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"
    mode: '0755'
  changed_when: false

- name: 'Configure Nginx on the load balancer.'
  ansible.builtin.template:
    src: 'node-homepages-proxy.conf.j2'
    dest: '/etc/nginx/sites-enabled/node-homepages-proxy.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  delegate_to: "{{ groups['haproxy'][0] }}"
  run_once: true
  notify:
  - 'Restart Nginx on the load balancer.'

# Consul Service Discovery Registration
- name: 'Register node homepage with Consul service discovery.'
  ansible.builtin.template:
    src: '../../goldentooth.setup_consul/templates/consul-service-registration.json.j2'
    dest: '/etc/consul.d/{{ ansible_hostname }}-homepage-service.json'
    owner: 'consul'
    group: 'consul'
    mode: '0644'
  vars:
    consul_service_name: "{{ ansible_hostname }}-homepage"
    consul_service_port: 8090
    consul_service_tags:
      - goldentooth
      - homepage
      - status
      - node
      - http
    consul_service_type: homepage
    consul_service_protocol: http
    consul_service_health_path: /
    consul_service_health_http: "http://{{ ipv4_address }}:8090/"
  notify:
    - 'Reload Consul configuration.'

- name: 'Add Consul reload handler for node homepage service registration.'
  ansible.builtin.meta: flush_handlers
