---
- name: 'Install ACL support.'
  ansible.builtin.apt:
    pkg:
      - 'acl'
    state: 'present'

- name: 'Create web root directory.'
  ansible.builtin.file:
    path: "{{ node_homepage.web_root }}"
    state: 'directory'
    mode: '0755'
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"

- name: 'Sets default ACL for Nginx on web root directory.'
  ansible.posix.acl:
    path: "{{ node_homepage.web_root }}"
    entity: "{{ node_homepage.nginx.user }}"
    etype: 'user'
    permissions: 'rX'
    state: 'present'
    recursive: true
    default: true
  notify:
    - 'Restart Nginx.'

- name: 'Install nginx.'
  ansible.builtin.apt:
    pkg:
      - 'nginx'
    state: 'present'
  notify:
    - 'Restart Nginx.'

- name: 'Remove default Nginx server configuration.'
  ansible.builtin.file:
    dest: '/etc/nginx/sites-enabled/default'
    state: 'absent'
  notify:
    - 'Restart Nginx.'

- name: 'Configure Nginx.'
  ansible.builtin.template:
    src: 'node-homepage.conf.j2'
    dest: '/etc/nginx/sites-enabled/node-homepage.conf'
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"
    mode: '0644'
  notify:
    - 'Restart Nginx.'

- name: 'Copy index.html into place.'
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: "{{ node_homepage.web_root }}/index.html"
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"
    mode: '0755'

- name: 'Set the node 128x128 png.'
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ clean_hostname }}.png"
    dest: "{{ node_homepage.web_root }}/node.png"
    owner: "{{ node_homepage.nginx.user }}"
    group: "{{ node_homepage.nginx.group }}"
    mode: '0755'
  changed_when: false

- name: 'Configure Nginx on the load balancer.'
  ansible.builtin.template:
    src: 'node-homepages-proxy.conf.j2'
    dest: '/etc/nginx/sites-enabled/node-homepages-proxy.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  delegate_to: "{{ groups['load_balancer'][0] }}"
  run_once: true
  notify:
  - 'Restart Nginx on the load balancer.'
