---
- name: 'Set facts.'
  ansible.builtin.set_fact:
    argocd_password: "{{ vault.easy_password | password_hash('bcrypt') }}"

- name: 'Add Argo Helm chart repository.'
  kubernetes.core.helm_repository:
    name: 'argo'
    repo_url: "{{ argocd_chart_repo_url }}"

- name: 'Install the Argo CD command-line interface.'
  ansible.builtin.get_url:
    url: 'https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64'
    dest: '/usr/local/bin/argocd'
    mode: '0555'

- name: 'Create a Kubernetes secret for the GitHub token.'
  kubernetes.core.k8s:
    state: 'present'
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      metadata:
        name: 'github-token'
        namespace: 'argocd'
      type: 'Opaque'
      data:
        token: "{{ vault.github_token | b64encode }}"
  run_once: true

- name: 'Install Argo CD from Helm chart.'
  kubernetes.core.helm:
    atomic: true
    chart_ref: 'argo/argo-cd'
    chart_version: "{{ argocd_chart_version }}"
    create_namespace: true
    release_name: 'argocd'
    release_namespace: 'argocd'
    release_values: "{{ argocd_release_values }}"
    update_repo_cache: true
    wait: true
  run_once: true
