---
- name: 'Trigger systemd daemon-reload.'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart HAProxy.'
  ansible.builtin.systemd_service:
    name: 'haproxy'
    state: 'restarted'

- name: 'Restart rsyslog.'
  ansible.builtin.systemd_service:
    name: 'rsyslog'
    state: 'restarted'

- name: 'Restart HAProxy dataplane API.'
  ansible.builtin.systemd_service:
    name: 'haproxy-dataplaneapi'
    state: 'restarted'

- name: 'Restart Nginx.'
  ansible.builtin.systemd_service:
    name: 'nginx'
    state: 'restarted'