---
- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: Let iptables see bridged traffic.
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: 'Setup containerd.'
  ansible.builtin.include_role:
    name: 'geerlingguy.containerd'

- name: 'Create cluster.'
  ansible.builtin.include_role:
    name: 'geerlingguy.kubernetes'
