---
# This file was inspired by Max Hoesel's Ansible collection for Smallstep.
# See https://github.com/maxhoesel-ansible/ansible-collection-smallstep

- name: 'Install step-ca package and service.'
  ansible.builtin.include_role:
    name: 'goldentooth.install_step_ca'

- name: 'Look for existing configuration.'
  ansible.builtin.stat:
    path: "{{ step_ca.ca.ca_config_file_path }}"
  register: 'step_ca_config_file'

- name: 'Ensure intermediate password file is present.'
  ansible.builtin.copy:
    content: "{{ secret_vault.step_ca.passwords.intermediate }}"
    dest: "{{ step_ca.ca.password_file_paths.intermediate }}"
    owner: "{{ step_ca.ca.user }}"
    group: "{{ step_ca.ca.user }}"
    mode: 0600
  no_log: true

- name: 'Ensure JWK provisioner password file is present.'
  ansible.builtin.copy:
    content: "{{ secret_vault.step_ca.passwords.provisioners.jwk }}"
    dest: "{{ step_ca.ca.password_file_paths.default_provisioner }}"
    owner: "{{ step_ca.ca.user }}"
    group: "{{ step_ca.ca.user }}"
    mode: 0600
  no_log: true

- name: 'Initialize certificate authority.'
  block:

    - name: 'Create root key password file.'
      ansible.builtin.copy:
        content: "{{ secret_vault.step_ca.passwords.root }}"
        dest: "{{ step_ca.ca.password_file_paths.root }}"
        owner: "{{ step_ca.ca.user }}"
        group: "{{ step_ca.ca.user }}"
        mode: 0600
      no_log: true

    - name: 'Initialize Certificate Authority.'
      ansible.builtin.shell:
        cmd: |
          {{ step_ca.executable }} \
            ca init \
            --acme \
            --ssh \
            --name={{ step_ca.ca.name }} \
            --deployment-type=standalone \
            --dns={{ step_ca.ca.sans }} \
            --address={{ step_ca.ca.bind_address }} \
            --provisioner={{ step_ca.default_provisioner.name }} \
            --password-file={{ step_ca.ca.password_file_paths.root }} \
            --provisioner-password-file={{ step_ca.ca.password_file_paths.default_provisioner }}
      environment:
        STEPPATH: "{{ step_ca.ca.etc_path }}"
      become: true
      become_user: "{{ step_ca.ca.user }}"
      notify:
        - 'Restart step-ca service.'

    - name: 'Change password for intermediate and ssh keys.'
      ansible.builtin.shell:
        cmd: |
          {{ step_ca.executable }} \
            crypto change-pass {{ step_ca.ca.etc_path }}/secrets/{{ item }} \
            --force \
            --password-file={{ step_ca.ca.password_file_paths.root }} \
            --new-password-file={{ step_ca.ca.password_file_paths.intermediate }}
      loop:
        - 'intermediate_ca_key'
        - 'ssh_host_ca_key'
        - 'ssh_user_ca_key'
      loop_control:
        loop_var: 'item'
      become: true
      become_user: "{{ step_ca.ca.user }}"

  always:

    - name: 'Ensure root password file is absent.'
      ansible.builtin.file:
        path: "{{ step_ca.ca.password_file_paths.root }}"
        state: 'absent'

  when: 'not step_ca_config_file.stat.exists'

- name: 'Read file directly into fact.'
  ansible.builtin.slurp:
    src: "{{ step_ca.ca.ca_config_file_path }}"
  register: 'step_ca_config_file_base64'

- name: 'Set fact for step-ca config.'
  ansible.builtin.set_fact:
    step_ca_config: "{{ step_ca_config_file_base64.content | b64decode | from_json }}"

- name: 'Update the facts.'
  ansible.utils.update_fact:
    updates:
      - path: step_ca_config['authority']['claims']
        value: "{{ step_ca_config['authority']['claims'] | default({}) }}"
      - path: step_ca_config['authority']['claims']['maxTLSCertDuration']
        value: "168h"
  register: 'updated_config'

- name: 'Update the step-ca configuration.'
  ansible.builtin.copy:
    content: "{{ updated_config.step_ca_config | to_nice_json }}"
    dest: "{{ step_ca.ca.ca_config_file_path }}"
    owner: "{{ step_ca.ca.user }}"
    group: "{{ step_ca.ca.user }}"
    mode: 0644
  notify:
    - 'Restart step-ca service.'
