---
- name: 'Trigger systemd daemon-reload.'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart Grafana service.'
  ansible.builtin.systemd_service:
    name: 'grafana-server'
    state: 'restarted'

- name: 'Restart Nginx service.'
  ansible.builtin.systemd_service:
    name: 'nginx'
    state: 'restarted'
  delegate_to: "{{ groups['haproxy'] | first }}"