---
- name: 'Set facts.'
  ansible.builtin.set_fact:
    argocd_password: '$2a$10$JE9JSC22MXbj4qXmKhfXjOcWGDKvoVaRvdUa3PV3lj6cY8zD8mjku'

- name: 'Add Argo Helm chart repository.'
  kubernetes.core.helm_repository:
    name: 'argo'
    repo_url: "{{ argo_cd.chart_repo_url }}"

- name: 'Install the Argo CD command-line interface.'
  ansible.builtin.get_url:
    url: 'https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64'
    dest: '/usr/local/bin/argocd'
    mode: '0555'

- name: 'Create the Argo CD namespace.'
  kubernetes.core.k8s:
    state: 'present'
    definition:
      apiVersion: 'v1'
      kind: 'Namespace'
      metadata:
        name: "{{ argo_cd.namespace }}"
  run_once: true

- name: 'Create a Kubernetes secret for the GitHub token.'
  kubernetes.core.k8s:
    state: 'present'
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      metadata:
        name: 'github-token'
        namespace: "{{ argo_cd.namespace }}"
      type: 'Opaque'
      data:
        token: "{{ secret_vault.github_token | b64encode }}"
  run_once: true

- name: 'Install Argo CD from Helm chart.'
  kubernetes.core.helm:
    atomic: false
    chart_ref: 'argo/argo-cd'
    chart_version: "{{ argo_cd.chart_version }}"
    create_namespace: true
    release_name: 'argocd'
    release_namespace: "{{ argo_cd.namespace }}"
    release_values: "{{ argo_cd.release_values }}"
    update_repo_cache: true
    wait: false
  run_once: true
