---
# Generic Ansible variables
# #############################################################################

# user to connect to via SSH
ansible_user: 'root'

# Common vars that are used in Kubespray
# #############################################################################

# Specify a given Kubernetes version
kube_version: 'v1.29.1'

# Download and install the specified version of kubectl locally
kubectl_localhost: true

# Download cluster configuration file locally
kubeconfig_localhost: true

# Array of DNS domains to search when looking up hostnames
# searchdomains

# Addressing variables
# #############################################################################

# If defined, all hosts will connect to this address instead of localhost for
# kube_control_planes and kube_control_plane[0] for kube_nodes.
loadbalancer_apiserver:
  address: "{{ load_balancer.ipv4_address }}"
  port: 6443

# Cluster variables
# #############################################################################

# Name of cluster (default is cluster.local)
cluster_name: 'goldentooth'

# Name of cluster DNS domain (default is cluster.local)
dns_domain: "{{ cluster_name }}.{{ my.domain.private }}"

# DNS variables
# #############################################################################

# Array of upstream DNS servers configured on host in addition to Kubespray
# deployed DNS.
upstream_dns_servers:
  - '10.4.0.1'
  - '8.8.4.4'
  - '8.8.8.8'

# Auto rotate the kubelet client certificates by requesting new certificates
# from the kube-apiserver when the certificate expiration approaches.
kubelet_rotate_certificates: true

# Auto rotate the kubelet server certificates by requesting new certificates
# from the kube-apiserver when the certificate expiration approaches. Note that
# enabling this also activates `kubelet_csr_approver` which automatically
# approves the CSRs.
#
# To customize its behavior, you can override the Helm values via
# kubelet_csr_approver_values. See kubelet-csr-approver for more information.
kubelet_rotate_server_certificates: true

# MetalLB variables
# #############################################################################

# You have to configure arp_ignore and arp_announce to avoid answering ARP
# queries from kube-ipvs0 interface for MetalLB to work.
kube_proxy_strict_arp: true

# You have to explicitly enable the MetalLB extension.
metallb_enabled: true
metallb_speaker_enabled: true

metallb_config:
  # By default only the MetalLB BGP speaker is allowed to run on control plane
  # nodes. If you have a single node cluster or a cluster where control plane
  # are also worker nodes you may need to enable tolerations for the MetalLB
  # controller:
  #
  # controller:
  #   nodeselector:
  #     kubernetes.io/os: linux
  #   tolerations:
  #   - key: "node-role.kubernetes.io/control-plane"
  #     operator: "Equal"
  #     value: ""
  #     effect: "NoSchedule"
  address_pools:
    primary:
      ip_range:
        - 10.4.1.0/24
      auto_assign: true
      avoid_buggy_ips: true
  layer2:
    - 'primary'
