---
- name: 'Restart Nginx.'
  ansible.builtin.systemd_service:
    name: 'nginx'
    state: 'restarted'

- name: 'Restart Nginx on the load balancer.'
  ansible.builtin.systemd_service:
    name: 'nginx'
    state: 'restarted'
  delegate_to: "{{ groups['haproxy'][0] }}"

- name: 'Reload Consul configuration.'
  ansible.builtin.systemd_service:
    name: 'consul'
    state: 'reloaded'