---
- name: 'Reset Kubernetes cluster with kubeadm.'
  ansible.builtin.command:
    cmd: 'kubeadm reset --force'
  failed_when: false
  when: 'inventory_hostname != load_balancer.hostname'
  changed_when: false

- name: 'Remove Kubernetes directory and its contents.'
  ansible.builtin.file:
    path: '/etc/kubernetes'
    state: 'absent'
