---
- name: 'Set the MOTD.'
  ansible.builtin.template:
    src: "{{ role_path }}/files/{{ clean_hostname }}.txt"
    dest: '/etc/motd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  changed_when: false
  become: true
