---
- name: 'Install rsyslog.'
  ansible.builtin.apt:
    name:
      - 'rsyslog'
    state: 'present'
    cache_valid_time: 3600
  notify: 'Restart rsyslog.'

- name: 'Install HAProxy.'
  ansible.builtin.apt:
    name:
      - 'haproxy'
    state: 'present'
    cache_valid_time: 3600
  notify: 'Restart HAProxy.'

- name: 'Install other packages.'
  ansible.builtin.apt:
    name:
      - 'python3-passlib'
    state: 'present'
    cache_valid_time: 3600

- name: 'Ensure HAProxy certificate directory exists.'
  ansible.builtin.file:
    path: '/etc/haproxy/tls'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Ensure HAProxy service directory exists.'
  ansible.builtin.file:
    path: '/etc/systemd/system/cert-renewer@haproxy.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Enable cert-renewer service for HAProxy.'
  ansible.builtin.systemd_service:
    name: 'cert-renewer@haproxy.timer'
    enabled: true
    state: 'started'
  notify:
    - 'Trigger systemd daemon-reload.'

- name: 'Copy HAProxy certificate renewer configuration into place.'
  ansible.builtin.template:
    src: 'cert-renewer@haproxy.conf.j2'
    dest: '/etc/systemd/system/cert-renewer@haproxy.service.d/override.conf'
  notify:
    - 'Trigger systemd daemon-reload.'

- name: 'Ensure SSL private directory exists.'
  ansible.builtin.file:
    path: '/etc/ssl/private'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: 'Generate initial HAProxy certificate.'
  ansible.builtin.shell: |
    step ca certificate \
      "*.{{ cluster.services_domain }}" \
      /etc/haproxy/tls/tls.crt \
      /etc/haproxy/tls/tls.key \
      --provisioner="default" \
      --password-file="/root/.step/jwk_provisioner_password.txt" \
      --san="*.{{ cluster.services_domain }}" \
      --san="{{ ansible_hostname }}" \
      --san="{{ ansible_hostname }}.{{ cluster.node_domain }}" \
      --san="{{ ipv4_address }}" \
      --not-after='24h' \
      --console \
      --force
  args:
    creates: /etc/haproxy/tls/tls.crt
  notify:
    - 'Restart HAProxy.'

- name: 'Create combined certificate with full chain for HAProxy.'
  ansible.builtin.shell: |
    cat /etc/haproxy/tls/tls.crt > /tmp/haproxy_chain.pem && \
    step ca root >> /tmp/haproxy_chain.pem && \
    cat /tmp/haproxy_chain.pem /etc/haproxy/tls/tls.key > /etc/ssl/private/goldentooth.pem && \
    chown haproxy:haproxy /etc/ssl/private/goldentooth.pem && \
    chmod 600 /etc/ssl/private/goldentooth.pem && \
    rm /tmp/haproxy_chain.pem
  args:
    creates: /etc/ssl/private/goldentooth.pem
  notify:
    - 'Restart HAProxy.'

- name: 'Ensure HAProxy run directory exists.'
  ansible.builtin.file:
    path: '/var/run/haproxy'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Configure HAProxy.'
  ansible.builtin.template:
    src: 'haproxy.cfg.j2'
    dest: '/etc/haproxy/haproxy.cfg'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart HAProxy.'

- name: 'Create HAProxy dataplane API directory.'
  ansible.builtin.file:
    path: '/etc/haproxy-dataplane'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Create HAProxy dataplane storage directory.'
  ansible.builtin.file:
    path: '/etc/haproxy/dataplane'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Create HAProxy maps directory.'
  ansible.builtin.file:
    path: '/etc/haproxy/maps'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Create HAProxy SSL directory.'
  ansible.builtin.file:
    path: '/etc/haproxy/ssl'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Create additional HAProxy dataplane directories.'
  ansible.builtin.file:
    path: '/etc/haproxy/{{ item }}'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'
  loop:
    - 'general'
    - 'spoe'
    - 'acl'
    - 'transactions'

- name: 'Create SPOE temporary directory.'
  ansible.builtin.file:
    path: '/tmp/spoe-haproxy'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Download HAProxy dataplane API binary.'
  ansible.builtin.get_url:
    url: 'https://github.com/haproxytech/dataplaneapi/releases/download/v3.2.1/dataplaneapi_3.2.1_linux_{% if ansible_architecture == "aarch64" %}arm64{% else %}{{ ansible_architecture }}{% endif %}.tar.gz'
    dest: '/tmp/dataplaneapi.tar.gz'
    mode: '0644'
    timeout: 60

- name: 'Extract HAProxy dataplane API binary.'
  ansible.builtin.unarchive:
    src: '/tmp/dataplaneapi.tar.gz'
    dest: '/tmp'
    remote_src: yes
    creates: '/tmp/dataplaneapi'

- name: 'Install HAProxy dataplane API binary.'
  ansible.builtin.copy:
    src: '/tmp/dataplaneapi'
    dest: '/usr/local/bin/haproxy-dataplaneapi'
    remote_src: yes
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Configure HAProxy dataplane API.'
  ansible.builtin.template:
    src: 'dataplaneapi.yaml.j2'
    dest: '/etc/haproxy-dataplane/dataplaneapi.yaml'
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0600'
  notify: 'Restart HAProxy dataplane API.'

- name: 'Create HAProxy transaction directory.'
  ansible.builtin.file:
    path: '/tmp/haproxy'
    state: directory
    owner: 'haproxy'
    group: 'haproxy'
    mode: '0755'

- name: 'Create HAProxy dataplane API systemd service.'
  ansible.builtin.template:
    src: 'haproxy-dataplaneapi.service.j2'
    dest: '/etc/systemd/system/haproxy-dataplaneapi.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Trigger systemd daemon-reload.'
    - 'Restart HAProxy dataplane API.'

- name: 'Enable and start HAProxy dataplane API service.'
  ansible.builtin.systemd_service:
    name: 'haproxy-dataplaneapi'
    enabled: yes
    state: started
    daemon_reload: yes

- name: 'Install Nginx.'
  ansible.builtin.apt:
    name:
      - 'nginx'
    state: 'present'
    cache_valid_time: 3600
  notify: 'Restart Nginx.'

- name: 'Create Nginx basic auth file.'
  community.general.htpasswd:
    path: '/etc/nginx/.htpasswd'
    name: "{{ my.name.lower }}"
    password: "{{ secret_vault.easy_password }}"
    owner: "{{ haproxy.nginx.user }}"
    group: "{{ haproxy.nginx.group }}"
    mode: 0640

- name: 'Remove legacy nginx configurations.'
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/{{ template }}.conf"
    state: absent
  loop:
    - 'basic_auth_gateway'
    - 'zzz_metallb_services'
  loop_control:
    loop_var: 'template'
  notify: 'Restart Nginx.'
