---
- name: 'Install necessary packages.'
  ansible.builtin.apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gpg'
    state: 'present'
    cache_valid_time: 3600
  become: true

- name: 'Ensure `/etc/apt/keyrings` directory exists.'
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: 'directory'
    mode: '0755'
  become: true

- name: 'Download the Kubernetes signing key.'
  ansible.builtin.get_url:
    url: "{{ k8s_apt_repository_key_url }}"
    dest: "{{ k8s_apt_repository_key_tmp_path }}"
  become: true

- name: Add Kubernetes Release Key to the apt keyring
  ansible.builtin.apt_key:
    file: "{{ k8s_apt_repository_key_tmp_path }}"
    keyring: "{{ k8s_apt_repository_keyring_path }}"
    state: 'present'
  become: true

- name: 'Add Kubernetes apt repository.'
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ k8s_apt_repository_keyring_path }}] {{ k8s_apt_repository_url }} /"
    state: present
    filename: 'kubernetes'
  become: true
  register: k8s_repo

- name: 'Update apt cache.'
  ansible.builtin.apt:
    update_cache: true
  when: 'k8s_repo.changed'
  become: true