---
- name: 'Install required packages.'
  ansible.builtin.apt:
    name:
      - 'nfs-common'

- name: 'Create mountpoint.'
  ansible.builtin.file:
    path: '/mnt/nfs'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: 'Setup service for mount.'
  ansible.builtin.template:
    src: 'mount.j2'
    dest: "/etc/systemd/system/{{ item.value.safe_name }}.mount"
  loop: "{{ nfs.mounts | dict2items }}"
  loop_control:
    loop_var: 'item'
  notify:
    - 'Restart NFS mount.'

- name: 'Setup systemd service for automount.'
  ansible.builtin.template:
    src: 'automount.j2'
    dest: "/etc/systemd/system/{{ item.value.safe_name }}.automount"
  loop: "{{ nfs.mounts | dict2items }}"
  loop_control:
    loop_var: 'item'
  notify:
    - 'Restart NFS automount.'
