---
- name: 'Check for existence of ZFS pool with specified name.'
  ansible.builtin.command:
    cmd: 'zpool list {{ zfs.pool.name }}'
  register: 'zfs_pool_check'
  ignore_errors: true
  changed_when: false

- name: 'Create a new primary partition on /dev/sda.'
  community.general.parted:
    device: '/dev/sda'
    number: 1
    state: 'present'
    part_type: 'primary'
    fs_type: 'zfs'
    resize: true
  when: 'zfs_pool_check.rc != 0'

- name: 'Ensure that ZFS packages are installed.'
  ansible.builtin.apt:
    pkg:
      - 'sanoid'
      - 'zfsutils-linux'
      - 'zfs-dkms'
      - 'zfs-zed'
    state: 'present'
  notify:
    - 'Restart ZFS-zed service.'

- name: "Set ARC max for low-memory system"
  ansible.builtin.copy:
    dest: /etc/modprobe.d/zfs.conf
    content: "options zfs zfs_arc_max={{ zfs.arc_max }}\n"
    mode: '0644'
  notify: 'Update initramfs.'

- name: 'Ensure ZFS module is loaded.'
  ansible.builtin.modprobe:
    name: 'zfs'
    state: 'present'

- name: 'Create ZFS pool.'
  ansible.builtin.command:
    cmd: "zpool create -f {{ zfs.pool.name }} {{ zfs.pool.device }}"
  when: zfs_pool_check.rc != 0

- name: 'Create datasets.'
  block:
    - name: "Check if dataset exists"
      ansible.builtin.command: |
        zfs list {{ zfs.pool.name }}/{{ item.name }}
      register: dataset_check
      loop: "{{ zfs.datasets }}"
      loop_control:
        label: "{{ item.name }}"
      ignore_errors: true
      changed_when: false

    - name: "Create dataset."
      ansible.builtin.command: |
        zfs create -o mountpoint={{ item.item.mountpoint }} {{ zfs.pool.name }}/{{ item.item.name }}
      when: item.rc != 0
      loop: "{{ dataset_check.results }}"
      loop_control:
        label: "{{ item.item.name }}"
  when: inventory_hostname == groups['zfs'][0]  # Only create datasets on primary

- name: 'Ensure sanoid configuration directory exists.'
  ansible.builtin.file:
    path: '/etc/sanoid'
    state: 'directory'
    mode: '0755'
  when: inventory_hostname == groups['zfs'][0]  # Only on primary

- name: 'Copy Sanoid defaults file into place.'
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sanoid.defaults.conf"
    dest: '/etc/sanoid/sanoid.defaults.conf'
    mode: '0644'
  when: inventory_hostname == groups['zfs'][0]  # Only on primary

- name: 'Copy Sanoid conf file into place.'
  ansible.builtin.template:
    src: 'sanoid.conf.j2'
    dest: '/etc/sanoid/sanoid.conf'
    mode: '0644'
  when: inventory_hostname == groups['zfs'][0]  # Only on primary

- name: 'Enable Sanoid timer.'
  ansible.builtin.systemd:
    name: 'sanoid.timer'
    enabled: true
    state: 'started'
  when: inventory_hostname == groups['zfs'][0]  # Only on primary

# Configure Syncoid for ZFS replication between nodes
- name: 'Configure Syncoid systemd service for ZFS replication.'
  ansible.builtin.template:
    src: 'syncoid.service.j2'
    dest: '/etc/systemd/system/syncoid@.service'
    mode: '0644'
  notify: 'Reload systemd daemon.'

- name: 'Configure Syncoid systemd timer for ZFS replication.'
  ansible.builtin.template:
    src: 'syncoid.timer.j2'
    dest: '/etc/systemd/system/syncoid@.timer'
    mode: '0644'
  notify: 'Reload systemd daemon.'

- name: 'Configure SSH config for ZFS replication using certificates.'
  ansible.builtin.blockinfile:
    path: '/root/.ssh/config'
    create: true
    mode: '0600'
    block: |
      # ZFS replication configuration using SSH certificates
      {% for host in groups['zfs'] %}
      {% if host != inventory_hostname %}
      Host {{ host }}
        HostName {{ hostvars[host]['ipv4_address'] }}
        User root
        CertificateFile /etc/step/certs/root_ssh_key-cert.pub
        IdentityFile /etc/step/certs/root_ssh_key
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
      {% endif %}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ZFS Replication"

- name: 'Reload systemd daemon.'
  ansible.builtin.systemd:
    daemon_reload: true
  when: groups['zfs'] | length > 1

- name: 'Enable and start Syncoid timers for replication targets.'
  ansible.builtin.systemd:
    name: "syncoid@{{ item }}.timer"
    enabled: true
    state: 'started'
  loop: "{{ groups['zfs'] | reject('eq', inventory_hostname) | list }}"
  when: 
    - groups['zfs'] | length > 1
    - inventory_hostname == groups['zfs'][0]  # Only run on first ZFS node (allyrion)
