# Fan
# 
# Set the behaviour of a GPIO connected fan.
#
# `sudo raspi-config nonint do_fan <0/1> [gpio] [onTemp]`
# - 0 - Enable fan
# - 1 - Disable fan
#
# `gpio` defaults to 14.
# 
# `onTemp` defaults to 80 °C.
# 
pi_fan_gpio: 14
pi_fan_temp: 60

# Locale
#
# Select a locale, for example `en_US.UTF-8 UTF-8`.
pi_locale: 'en.US-UTF-8'

# Time Zone
#
# Select a time zone, for example `America/New_York`.
pi_timezone: 'America/New_York'

# Keyboard
#
# Select a keyboard layout, for example `us`.
pi_keyboard: 'us'

# WLAN Country
#
# Select a WLAN country, for example `US`.
pi_wlan_country: 'US'

# Overclock Frequency
#
# Set the overclocking frequency.
pi_overclock_freq: '2000'

# Overclock Voltage
#
# Set the overclocking voltage.
pi_overclock_voltage: '6'
