---
- name: 'Generate certificate for Vault from step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca_executable }} \
        ca certificate \
        vault.service.consul \
        "{{ vault_cert_path }}" \
        "{{ vault_key_path }}" \
        --provisioner="{{ step_ca_provisioner }}" \
        --password-file="{{ step_ca_provisioner_password_path }}" \
        --san='vault.service.consul' \
        --san='localhost' \
        --san="{{ clean_hostname }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force

- name: 'Repair permissions on Vault certs.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'file'
    owner: 'vault'
    group: 'vault'
    mode: '0600'
  loop:
    - "{{ vault_cert_path }}"
    - "{{ vault_key_path }}"
  loop_control:
    loop_var: 'item'
