---
- name: 'Ensure directory for Vault certs exists.'
  ansible.builtin.file:
    path: "{{ vault.certs_path }}"
    state: 'directory'
    owner: 'vault'
    group: 'vault'
    mode: '0755'

- name: 'Generate certificate for Vault from step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca.executable }} \
        ca certificate \
        vault.service.consul \
        "{{ vault.cert_path }}" \
        "{{ vault.key_path }}" \
        --provisioner="{{ step_ca.default_provisioner.name }}" \
        --password-file="{{ step_ca.default_provisioner.password_path }}" \
        --san='vault.service.consul' \
        --san='localhost' \
        --san="{{ clean_hostname }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force

- name: 'Repair permissions on Vault certs.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'file'
    owner: 'vault'
    group: 'vault'
    mode: '0600'
  loop:
    - "{{ vault.cert_path }}"
    - "{{ vault.key_path }}"
  loop_control:
    loop_var: 'item'
