---
- name: 'Generate certificate for Vault from step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca_executable }} \
        ca certificate \
        vault.service.consul \
        "{{ vault_certs_path }}/tls.crt" \
        "{{ vault_certs_path }}/tls.key" \
        --provisioner="{{ step_ca_provisioner }}" \
        --password-file="{{ step_ca_provisioner_password_path }}" \
        --san='vault.service.consul' \
        --san='localhost' \
        --san="{{ clean_hostname }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force
