---
- name: 'Update the Consul policies.'
  community.general.consul_policy:
    host: "{{ consul.maybe_leader }}"
    token: "{{ secret_vault.consul.mgmt_token }}"
    name: "{{ policy.name }}"
    description: "{{ policy.description }}"
    rules: "{{ policy.rules }}"
  loop:
    - name: 'nomad-client'
      description: 'Nomad client policy'
      rules: "{{ lookup('ansible.builtin.file', role_path ~ '/files/nomad.client.policy.hcl') }}"
    - name: 'nomad-server'
      description: 'Nomad server policy'
      rules: "{{ lookup('ansible.builtin.file', role_path ~ '/files/nomad.server.policy.hcl') }}"
  loop_control:
    loop_var: 'policy'
  run_once: true

- name: 'Create Consul tokens.'
  community.general.consul_token:
    host: "{{ consul.maybe_leader }}"
    scheme: 'http'
    validate_certs: false
    port: 8500
    token: "{{ secret_vault.consul.mgmt_token }}"
    description: "Nomad {{ nomad.role }} token"
    policies:
      - name: 'nomad-{{ nomad.role }}'
  register: 'nomad_consul_token'

- name: 'Copy Nomad service configuration into place on all nodes.'
  ansible.builtin.template:
    src: 'nomad.service.j2'
    dest: '/etc/systemd/system/nomad.service'
    owner: 'nomad'
    group: 'nomad'
    mode: '0644'
  notify:
    - 'Trigger systemd daemon-reload.'
    - 'Restart Nomad service.'

- name: 'Generate the gossip encryption key.'
  ansible.builtin.command:
    cmd: 'nomad operator gossip keyring generate'
  no_log: true
  run_once: true
  register: 'nomad_gossip_key'

- name: 'Copy Nomad configuration into place on all nodes.'
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    owner: 'nomad'
    group: 'nomad'
    mode: '0600'
  loop:
    - src: 'nomad.hcl.j2'
      dest: "{{ nomad.hcl_config_path }}"
    - src: 'nomad.env.j2'
      dest: "{{ nomad.env_config_path }}"
  loop_control:
    loop_var: 'file'
  notify:
    - 'Restart Nomad service.'

- name: 'Set Nomad environment variables in ~/.bashrc.'
  ansible.builtin.lineinfile:
    path: '~/.bashrc'
    regexp: "^export {{ variable.name }}"
    line: "export {{ variable.name }}={{ variable.value}}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - name: 'NOMAD_ADDR'
      value: "https://{{ groups['nomad_server'] | first }}:4646"
    - name: 'NOMAD_CACERT'
      value: "{{ step_ca.root_cert_path }}"
    - name: 'NOMAD_CLIENT_CERT'
      value: "{{ nomad.cli_cert_path }}"
    - name: 'NOMAD_CLIENT_KEY'
      value: "{{ nomad.cli_key_path }}"
  loop_control:
    loop_var: 'variable'

- name: 'Add Nomad-relevant line in ~/.bashrc.'
  ansible.builtin.lineinfile:
    path: '~/.bashrc'
    line: 'complete -C /usr/bin/nomad nomad'
    regexp: '^complete -C \/usr\/bin\/nomad nomad'
    state: 'present'
