# Description: Setup Vector Apt Repo.

- name: 'Setup Vector Apt Repo.'
  hosts: 'all'
  remote_user: 'root'
  tasks:

    - name: 'Add Vector repository.'
      ansible.builtin.deb822_repository:
        name: 'vector'
        types: ['deb']
        uris: ['https://apt.vector.dev/']
        suites: ['stable']
        components: ['vector-0']
        architectures: ['arm64']
        signed_by: "https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public"
        state: 'present'
        enabled: true
      notify:
        - 'Update Apt cache.'

  handlers:
    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true
