# Description: Setup Envoy package repositories for Apt.

- name: 'Setup Envoy package repositories for Apt.'
  hosts: 'envoy'
  remote_user: 'root'
  tasks:

    - name: 'Add Envoy repository.'
      ansible.builtin.deb822_repository:
        name: 'envoy'
        types: ['deb']
        uris: ['https://apt.envoyproxy.io']
        suites: ["{{ ansible_distribution_release | lower }}"]
        components: ['main']
        architectures: ['arm64']
        signed_by: "https://apt.envoyproxy.io/signing.key"
        state: 'present'
        enabled: true
      notify:
        - 'Update Apt cache.'

  handlers:
    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true
