# Description: Setup HashiCorp Apt Repo.

- name: 'Setup HashiCorp Apt Repo.'
  hosts: 'consul'
  remote_user: 'root'
  tasks:

    - name: 'Add HashiCorp repository.'
      ansible.builtin.deb822_repository:
        name: 'hashicorp'
        types: ['deb']
        uris: ['https://apt.releases.hashicorp.com/']
        suites: ["{{ ansible_distribution_release | lower }}"]
        components: ['main']
        architectures: ['arm64']
        signed_by: "https://apt.releases.hashicorp.com/gpg"
        state: 'present'
        enabled: true
      notify:
        - 'Update Apt cache.'

  handlers:
    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true
