# Description: Setup Grafana Apt Repo.

- name: 'Setup Grafana Apt Repo.'
  hosts: 'all'
  remote_user: 'root'
  tasks:

    - name: 'Add Grafana repository.'
      ansible.builtin.deb822_repository:
        name: 'grafana'
        types: ['deb']
        uris: ['https://apt.grafana.com/']
        suites: ['stable']
        components: ['main']
        architectures: ['arm64']
        signed_by: "https://apt.grafana.com/gpg.key"
        state: 'present'
        enabled: true
      notify:
        - 'Update Apt cache.'

  handlers:
    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true
