# Description: Setup Kubernetes package repositories for Apt.

- name: 'Setup Kubernetes package repositories for Apt.'
  hosts: 'k8s_cluster'
  remote_user: 'root'
  tasks:

    - name: 'Add Kubernetes repository.'
      ansible.builtin.deb822_repository:
        name: 'kubernetes'
        types: ['deb']
        uris: ["{{ kubernetes.apt_repo_url }}"]
        suites: ['/']
        architectures: ['arm64']
        signed_by: "{{ kubernetes.apt_repo_url }}/Release.key"
      notify:
        - 'Update Apt cache.'

  handlers:

    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true
