# Description: Setup Smallstep Apt Repo.

- name: 'Setup Smallstep Apt Repo.'
  hosts: 'consul'
  remote_user: 'root'
  tasks:

    - name: 'Add Smallstep Apt Repository.'
      ansible.builtin.deb822_repository:
        name: 'smallstep'
        types: ['deb']
        uris: ['https://packages.smallstep.com/stable/debian']
        suites: ['debs']
        components: ['main']
        architectures: ['arm64']
        signed_by: 'https://packages.smallstep.com/keys/apt/repo-signing-key.gpg'
        state: 'present'
        enabled: true
      notify:
        - 'Update Apt cache.'

  handlers:
    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true
