---
- name: 'Execute command with proper environment'
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: true
  tasks:

    - name: 'Execute command'
      ansible.builtin.shell:
        cmd: bash -l -c '{{ command_to_run }}'
        executable: /bin/bash
      register: command_output
      ignore_errors: true

    - name: 'Display command output'
      ansible.builtin.debug:
        msg: |-
          {{ command_output.stdout | default('No output') }}
          {{ command_output.stderr | default('No error output') }}
      register: command_output
