# Description: Connect Nomad and Consul.

- name: 'Connect Nomad and Consul.'
  hosts: 'all'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.connect_nomad_consul' }
  handlers:
    - name: 'Restart Consul service.'
      ansible.builtin.systemd:
        name: 'consul'
        state: 'restarted'
        enabled: true

    - name: 'Restart Nomad service.'
      ansible.builtin.systemd:
        name: 'nomad'
        state: 'restarted'
        enabled: true

