# Description: Install Kubernetes packages.

- name: 'Setup `containerd`.'
  hosts: 'k8s_cluster'
  remote_user: 'root'
  roles:
    - { role: 'geerlingguy.containerd' }

- name: 'Install Kubernetes packages.'
  hosts: 'k8s_cluster'
  remote_user: 'root'
  tasks:

    - name: 'Install Kubernetes packages.'
      ansible.builtin.apt:
        name: "{{ kubernetes.apt_packages }}"
        state: 'present'
      notify:
        - 'Hold Kubernetes packages.'
        - 'Enable and restart kubelet service.'

  handlers:
    - name: 'Update Apt cache.'
      ansible.builtin.apt:
        update_cache: true

    - name: 'Hold Kubernetes packages.'
      ansible.builtin.dpkg_selections:
        name: "{{ package }}"
        selection: 'hold'
      loop: "{{ kubernetes.apt_packages }}"
      loop_control:
        loop_var: 'package'

    - name: 'Enable and restart kubelet service.'
      ansible.builtin.systemd_service:
        name: 'kubelet'
        state: 'restarted'
        enabled: true
        daemon_reload: true
