# Description: Install Smallstep packages.

- name: 'Install Smallstep packages (`step` and `step-ca`).'
  hosts: 'step_ca'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.install_step_ca' }
  handlers:

    - name: 'Restart step-ca service.'
      ansible.builtin.systemd_service:
        name: 'step-ca'
        state: 'restarted'
        daemon_reload: true
        enabled: true
