# Description: Install HashiCorp Consul.

- name: 'Install HashiCorp Consul.'
  hosts: 'consul'
  remote_user: 'root'
  tasks:

    - name: 'Install Consul.'
      ansible.builtin.apt:
        pkg:
          - 'consul'
        state: 'present'
