# Description: Rotate Nomad TLS certificates.

- name: 'Rotate Nomad TLS certificates.'
  hosts: 'nomad'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.rotate_nomad_certs' }
  handlers:

    - name: 'Restart Nomad service.'
      ansible.builtin.systemd_service:
        name: 'nomad'
        state: 'restarted'
        enabled: true
