# Description: Rotate Vault TLS certificates.

- name: 'Rotate Vault TLS certificates.'
  hosts: 'vault'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.rotate_vault_certs' }
  handlers:

    - name: 'Restart Vault service.'
      ansible.builtin.systemd_service:
        name: 'vault'
        state: 'restarted'
        enabled: true
