# Description: Rotate Consul TLS certificates.

- name: 'Rotate Consul TLS certificates.'
  hosts: 'consul'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.rotate_consul_certs' }
  handlers:

    - name: 'Restart Consul service.'
      ansible.builtin.systemd:
        name: 'consul'
        state: 'restarted'
        enabled: true
