# Description: Install and configure Claude Code CLI on all cluster nodes.

- name: 'Setup Claude Code CLI'
  hosts: all
  remote_user: root
  gather_facts: true
  
  pre_tasks:
    - name: 'Verify Node.js is available'
      ansible.builtin.command: node --version
      register: nodejs_check
      changed_when: false
      failed_when: false
      
    - name: 'Install Node.js if not available'
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true
      when: nodejs_check.rc != 0
      
    - name: 'Verify npm is available'  
      ansible.builtin.command: npm --version
      register: npm_check
      changed_when: false
      failed_when: npm_check.rc != 0

  roles:
    - role: goldentooth.setup_claude_code

  post_tasks:
    - name: 'Display cluster-wide Claude Code summary'
      ansible.builtin.debug:
        msg: |
          Claude Code CLI deployment completed across Goldentooth cluster
          
          Installed on nodes: {{ groups['all'] | join(', ') }}
          
          Usage:
            claude --help         # Show Claude help (short command)
            claude chat           # Start interactive chat
            claude-code --help    # Full command name also works
            claude_help           # Show cluster-specific help
          
          Note: Users may need to set ANTHROPIC_API_KEY environment variable
          Note: 'cc' alias removed to avoid conflict with C compiler
      run_once: true
      delegate_to: localhost