# Description: Setup user accounts and their configurations.

- name: 'Configure general settings for the root user.'
  hosts: 'all'
  roles:
    - { role: 'goldentooth.setup_user' }
  remote_user: 'root'

- name: 'Configure general settings for the normie user.'
  hosts: 'all'
  roles:
    - { role: 'goldentooth.setup_user' }
  remote_user: "{{ my.name.lower }}"
