# Description: Setup Loki.

- name: 'Setup Loki.'
  hosts: 'loki'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_loki' }
  handlers:
    - name: 'Trigger systemd daemon-reload.'
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: 'Restart Loki service.'
      ansible.builtin.systemd_service:
        name: 'loki'
        state: 'restarted'
        enabled: true
        daemon_reload: true
