# Description: Setup HashiCorp Vault.

- name: 'Setup HashiCorp Vault.'
  hosts: 'all'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_vault' }
  handlers:

    - name: 'Trigger systemd daemon-reload.'
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: 'Restart Vault service.'
      ansible.builtin.systemd_service:
        name: 'vault'
        state: 'restarted'
        enabled: true
