---
# Playbook to setup Goldentooth MCP server
- name: Setup Goldentooth MCP Server
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Setup MCP server
      include_role:
        name: goldentooth.setup_mcp_server
      tags:
        - mcp
        - mcp_server
        - setup

  post_tasks:
    - name: Verify MCP server installation
      command: systemctl is-active goldentooth-mcp
      register: mcp_service_status
      changed_when: false
      failed_when: false

    - name: Display installation results
      debug:
        msg: |
          MCP Server deployment completed on {{ inventory_hostname }}
          Service status: {{ mcp_service_status.stdout | default('unknown') }}
          Architecture: {{ ansible_architecture }}
      tags:
        - always