# Description: Setup HAProxy.

- name: 'Setup HAProxy.'
  hosts: 'haproxy'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_haproxy' }
  handlers:
    - name: 'Restart HAProxy.'
      ansible.builtin.service:
        name: 'haproxy'
        state: 'restarted'
        enabled: true

    - name: 'Restart Nginx.'
      ansible.builtin.service:
        name: 'nginx'
        state: 'restarted'
        enabled: true

    - name: 'Restart rsyslog.'
      ansible.builtin.service:
        name: 'rsyslog'
        state: 'restarted'
        enabled: true
