# Description: Setup Consul.

- name: 'Install HashiCorp Consul.'
  hosts: 'consul'
  remote_user: 'root'
  tasks:

    - name: 'Install Consul.'
      ansible.builtin.apt:
        pkg:
          - 'consul'
        state: 'present'

- name: 'Setup Consul.'
  hosts: 'consul'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_consul' }
  handlers:

    - name: 'Trigger systemd daemon-reload.'
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: 'Restart Consul service.'
      ansible.builtin.systemd_service:
        name: 'consul'
        state: 'restarted'
        enabled: true

