# Description: Setup Grafana.

- name: 'Setup Grafana.'
  hosts: 'grafana'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_grafana' }
  handlers:
    - name: 'Trigger systemd daemon-reload.'
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: 'Restart Grafana service.'
      ansible.builtin.systemd_service:
        name: 'grafana-server'
        state: 'restarted'
        enabled: true
        force: true
        daemon_reload: true
