# Description: Setup Vector.

- name: 'Setup Vector.'
  hosts: 'all'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_vector' }
  handlers:

    - name: 'Trigger systemd daemon-reload.'
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: 'Restart Vector service.'
      ansible.builtin.systemd_service:
        name: 'vector'
        state: 'restarted'
        enabled: true
        daemon_reload: true
