---
- name: Setup cert-manager AWS credentials
  hosts: localhost
  gather_facts: false
  vars:
    cert_manager_namespace: cert-manager
  
  tasks:
    - name: Ensure cert-manager namespace exists
      kubernetes.core.k8s:
        name: "{{ cert_manager_namespace }}"
        api_version: v1
        kind: Namespace
        state: present
    
    - name: Create cert-manager AWS credentials secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cert-manager-aws-credentials
            namespace: "{{ cert_manager_namespace }}"
          type: Opaque
          data:
            access-key-id: "{{ secret_vault.aws.access_key_id | b64encode }}"
            secret-access-key: "{{ secret_vault.aws.secret_access_key | b64encode }}"
      no_log: true
    
    - name: Verify secret was created successfully
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: cert-manager-aws-credentials
        namespace: "{{ cert_manager_namespace }}"
      register: secret_info
    
    - name: Confirm secret creation
      debug:
        msg: "cert-manager AWS credentials secret created successfully"
      when: secret_info.resources | length > 0