# Description: Setup Consul ACL policies and tokens.

- name: 'Setup Consul ACL policies and tokens.'
  hosts: 'consul'
  remote_user: 'root'
  roles:
    - { role: 'goldentooth.setup_consul_acl' }
  handlers:
    - name: 'Restart Consul service.'
      ansible.builtin.systemd_service:
        name: 'consul'
        state: 'restarted'
        enabled: true