# Description: Sync kubeconfig to normal and root users on cluster nodes and local machine
---
- name: Sync kubeconfig to cluster nodes and local machine
  hosts: k8s_cluster
  become: true
  gather_facts: true
  vars:
    kubeconfig_source_path: "/etc/kubernetes/admin.conf"
    regular_user: "nathan"
    sync_to_local: true

  tasks:
    - name: Include kubeconfig sync role
      include_role:
        name: goldentooth.sync_kubeconfig

- name: Verify kubeconfig access
  hosts: k8s_cluster
  gather_facts: false
  tasks:
    - name: Test kubectl access as regular user
      command: kubectl cluster-info
      become: false
      register: kubectl_regular_result
      failed_when: kubectl_regular_result.rc != 0
      changed_when: false

    - name: Test kubectl access as root
      command: kubectl cluster-info
      become: true
      register: kubectl_root_result
      failed_when: kubectl_root_result.rc != 0
      changed_when: false

    - name: Display cluster info
      debug:
        msg: "Kubectl working for {{ inventory_hostname }}"