# Description: Upgrade Kubernetes.

- name: 'Upgrade kubeadm on first control plane node.'
  hosts: "{{ groups['control_plane'][0] }}"
  remote_user: 'root'
  handlers:
    - name: 'Hold kubeadm.'
      ansible.builtin.dpkg_selections:
        name: 'kubeadm'
        selection: 'hold'
  tasks:
    - name: 'Upgrade kubeadm (first control plane node).'
      ansible.builtin.include_role:
        name: 'goldentooth.upgrade_k8s'
      tags:
        - 'first_control_plane'

- name: 'Upgrade kubeadm on other control plane nodes.'
  hosts: "{{ groups['control_plane'][1:] | join(',') }}"
  remote_user: 'root'
  handlers:
    - name: 'Hold kubeadm.'
      ansible.builtin.dpkg_selections:
        name: 'kubeadm'
        selection: 'hold'
  tasks:
    - name: 'Upgrade kubeadm (other control plane nodes).'
      ansible.builtin.include_role:
        name: 'goldentooth.upgrade_k8s'
      tags:
        - 'other_control_plane'

- name: 'Upgrade kubelet on all nodes.'
  hosts: 'k8s_cluster'
  serial: 1
  remote_user: 'root'
  handlers:
    - name: 'Hold kubelet.'
      ansible.builtin.dpkg_selections:
        name: 'kubelet'
        selection: 'hold'
    - name: 'Restart kubelet.'
      ansible.builtin.systemd_service:
        name: 'kubelet'
        state: 'restarted'
        daemon_reload: true
        enabled: true
  tasks:
    - name: 'Upgrade kubelet.'
      ansible.builtin.include_role:
        name: 'goldentooth.upgrade_k8s'
      vars:
        control_plane_node: "{{ groups['control_plane'][0] }}"
      tags:
        - 'kubelet'

- name: 'Upgrade kubectl on control plane nodes.'
  hosts: 'control_plane'
  remote_user: 'root'
  handlers:
    - name: 'Hold kubectl.'
      ansible.builtin.dpkg_selections:
        name: 'kubectl'
        selection: 'hold'
  tasks:
    - name: 'Upgrade kubectl (all control plane nodes).'
      ansible.builtin.include_role:
        name: 'goldentooth.upgrade_k8s'
      tags:
        - 'kubectl'
