# Description: Delete the old cluster Certificate Authority.

- name: 'Zap Certificate Authority.'
  hosts: 'step_ca'
  remote_user: 'root'
  tasks:

    - name: 'Zap Certificate Authority.'
      ansible.builtin.file:
        path: "{{ step_ca_data_path }}"
        state: 'absent'
        force: true

  handlers:

    - name: 'Restart step-ca service.'
      ansible.builtin.systemd_service:
        name: 'step-ca'
        state: 'restarted'
        daemon_reload: true
        enabled: true
