---
# Unified Vector setup role - handles installation, certificates, and configuration

- name: 'Ensure Vector certificates are generated.'
  ansible.builtin.include_tasks: 'manage_certificates.yaml'

- name: 'Setup Vector.'
  ansible.builtin.apt:
    pkg:
      - 'vector'
    state: 'present'
  notify:
    - 'Restart Vector service.'

- name: 'Configure Vector service.'
  ansible.builtin.lineinfile:
    path: '/etc/systemd/system/multi-user.target.wants/vector.service'
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/vector --watch-config'
    state: 'present'
  notify:
    - 'Restart Vector service.'

- name: 'Configure Vector YAML.'
  ansible.builtin.template:
    src: 'vector.yaml.j2'
    dest: '/etc/vector/vector.yaml'
    owner: 'vector'
    group: 'vector'
    mode: '0644'
  notify:
    - 'Restart Vector service.'

- name: 'Grant Vector read access to /var/log/slurm.'
  ansible.posix.acl:
    path: '/var/log/slurm'
    entity: 'vector'
    etype: 'user'
    permissions: 'r'
    recursive: true
    state: 'present'
  ignore_errors: true

- name: 'Ensure Vector service directory exists.'
  ansible.builtin.file:
    path: '/etc/systemd/system/cert-renewer@vector.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Enable cert-renewer service for Vector.'
  ansible.builtin.systemd_service:
    name: 'cert-renewer@vector.timer'
    enabled: true
    state: 'started'
  notify:
    - 'Trigger systemd daemon-reload.'

- name: 'Copy Vector certificate renewer configuration into place on all nodes.'
  ansible.builtin.template:
    src: 'cert-renewer@vector.conf.j2'
    dest: '/etc/systemd/system/cert-renewer@vector.service.d/override.conf'
  notify:
    - 'Trigger systemd daemon-reload.'
