---
- name: 'Generate certificate for Nomad from step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca_executable }} \
        ca certificate \
        "{{ clean_hostname }}.global.nomad" \
        "{{ nomad_cert_path }}" \
        "{{ nomad_key_path }}" \
        --provisioner="{{ step_ca_provisioner }}" \
        --password-file="{{ step_ca_provisioner_password_path }}" \
        --san="{{ nomad_role }}.global.nomad" \
        --san='localhost' \
        --san="{{ clean_hostname }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force

- name: 'Generate certificate for Nomad CLI from step-ca.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca_executable }} \
        ca certificate \
        "{{ clean_hostname }}.cli.global.nomad" \
        "{{ nomad_cli_cert_path }}" \
        "{{ nomad_cli_key_path }}" \
        --provisioner="{{ step_ca_provisioner }}" \
        --password-file="{{ step_ca_provisioner_password_path }}" \
        --san='cli.global.nomad' \
        --san='localhost' \
        --san="{{ clean_hostname }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force

- name: 'Repair permissions on Nomad certs.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'file'
    owner: 'nomad'
    group: 'nomad'
    mode: '0600'
  loop:
    - "{{ nomad_cert_path }}"
    - "{{ nomad_key_path }}"
    - "{{ nomad_cli_cert_path }}"
    - "{{ nomad_cli_key_path }}"
  loop_control:
    loop_var: 'item'
