---
- name: 'Update Apt cache.'
  ansible.builtin.apt:
    update_cache: true
  tags:
    - 'kubeadm_first'
    - 'kubeadm_rest'
    - 'kubelet'
    - 'kubectl'

- name: 'Unhold kubeadm.'
  ansible.builtin.dpkg_selections:
    name: 'kubeadm'
    selection: 'install'
  tags:
    - 'kubeadm_first'
    - 'kubeadm_rest'

- name: 'Upgrade kubeadm on control plane nodes.'
  ansible.builtin.apt:
    name: 'kubeadm'
    state: 'latest'
  notify:
    - 'Hold kubeadm.'
  tags:
    - 'kubeadm_first'
    - 'kubeadm_rest'

- name: 'Drain node to upgrade kubelet.'
  kubernetes.core.k8s_drain:
    state: 'drain'
    name: "{{ clean_hostname }}"
    delete_options:
      terminate_grace_period: 900
      delete_emptydir_data: true
      ignore_daemonsets: true
  delegate_to: "{{ control_plane_node }}"
  tags:
    - 'kubelet'

- name: 'Unhold kubelet.'
  ansible.builtin.dpkg_selections:
    name: 'kubelet'
    selection: 'install'
  tags:
    - 'kubelet'

- name: 'Upgrade kubelet on node.'
  ansible.builtin.apt:
    name: 'kubelet'
    state: 'latest'
  notify:
    - 'Hold kubelet.'
    - 'Restart kubelet.'
  tags:
    - 'kubelet'

- name: 'Uncordon node.'
  kubernetes.core.k8s_drain:
    state: 'uncordon'
    name: "{{ clean_hostname }}"
  delegate_to: "{{ control_plane_node }}"
  tags:
    - 'kubelet'

- name: 'Unhold kubectl.'
  ansible.builtin.dpkg_selections:
    name: 'kubectl'
    selection: 'install'
  tags:
    - 'kubectl'

- name: 'Upgrade kubectl on control plane nodes.'
  ansible.builtin.apt:
    name: 'kubectl'
    state: 'latest'
  notify:
    - 'Hold kubectl.'
  tags:
    - 'kubectl'
