---
- name: 'Create/update the Vault Consul Policy.'
  community.general.consul_policy:
    host: "{{ groups['consul_server'][0] }}"
    token: "{{ vault.consul.mgmt_token }}"
    name: "{{ vault_consul_policy_name }}"
    description: 'Vault policy'
    rules: "{{ lookup('ansible.builtin.file', role_path ~ '/files/vault.policy.hcl') }}"
  run_once: true

- name: 'Create Consul client tokens.'
  community.general.consul_token:
    host: "{{ groups['consul_server'][0] }}"
    scheme: 'http'
    validate_certs: false
    port: 8500
    token: "{{ vault.consul.mgmt_token }}"
    description: "Vault token"
    policies:
      - name: "{{ vault_consul_policy_name }}"
  when: "clean_hostname in groups['vault']"
  register: 'vault_consul_token'

- name: 'Copy Vault service configuration into place on all nodes.'
  ansible.builtin.template:
    src: 'vault.service.j2'
    dest: "{{ vault_service_path }}"
    owner: 'vault'
    group: 'vault'
    mode: '0644'
  notify:
    - 'Trigger systemd daemon-reload.'
    - 'Restart Vault service.'

- name: 'Copy Vault configuration into place on all nodes.'
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    owner: 'vault'
    group: 'vault'
    mode: '0600'
  loop:
    - src: 'vault.hcl.j2'
      dest: "{{ vault_hcl_path }}"
    - src: 'vault.env.j2'
      dest: "{{ vault_env_path }}"
  loop_control:
    loop_var: 'file'
  notify:
    - 'Restart Vault service.'

- name: 'Set Vault environment variables in ~/.bashrc.'
  ansible.builtin.lineinfile:
    path: '~/.bashrc'
    regexp: "^export {{ variable.name }}"
    line: "export {{ variable.name }}={{ variable.value}}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - name: 'VAULT_ADDR'
      value: "https://{{ groups['vault'] | first }}:8200"
    - name: 'VAULT_CACERT'
      value: "{{ vault_certs_path }}/ca.crt"
    - name: 'VAULT_CLIENT_CERT'
      value: "{{ vault_certs_path }}/tls.crt"
    - name: 'VAULT_CLIENT_KEY'
      value: "{{ vault_certs_path }}/tls.key"
  loop_control:
    loop_var: 'variable'
