---
- name: 'Install Vault.'
  ansible.builtin.apt:
    pkg:
      - 'vault'
    state: 'present'

- name: 'Create/update the Vault Consul Policy.'
  community.general.consul_policy:
    host: "{{ ipv4_address }}"
    token: "{{ consul.mgmt_token }}"
    name: "{{ vault.consul.policy_name }}"
    description: 'Vault policy'
    rules: "{{ lookup('ansible.builtin.file', role_path ~ '/files/vault.policy.hcl') }}"
  run_once: true

- name: 'Create Consul client tokens.'
  community.general.consul_token:
    host: "{{ ipv4_address }}"
    token: "{{ consul.mgmt_token }}"
    description: "Vault token"
    policies:
      - name: "{{ vault.consul.policy_name }}"
  register: 'vault_consul_token'

- name: 'Copy Vault service configuration into place on all nodes.'
  ansible.builtin.template:
    src: 'vault.service.j2'
    dest: '/etc/systemd/system/vault.service'
    owner: 'vault'
    group: 'vault'
    mode: '0644'
  notify:
    - 'Trigger systemd daemon-reload.'
    - 'Restart Vault service.'

- name: 'Copy Vault configuration into place on all nodes.'
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    owner: 'vault'
    group: 'vault'
    mode: '0600'
  loop:
    - src: 'vault.hcl.j2'
      dest: "{{ vault.hcl_config_path }}"
    - src: 'vault.env.j2'
      dest: "{{ vault.env_config_path }}"
  loop_control:
    loop_var: 'file'
  notify:
    - 'Restart Vault service.'

- name: 'Set Vault environment variables in ~/.bashrc.'
  ansible.builtin.lineinfile:
    path: '~/.bashrc'
    regexp: "^export {{ variable.name }}"
    line: "export {{ variable.name }}={{ variable.value}}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - name: 'VAULT_ADDR'
      value: "https://{{ ipv4_address }}:8200"
    - name: 'VAULT_CLIENT_CERT'
      value: "{{ vault.cert_path }}"
    - name: 'VAULT_CLIENT_KEY'
      value: "{{ vault.key_path }}"
  loop_control:
    loop_var: 'variable'
