---
- name: 'Ensure directory for Prometheus client certificates exists.'
  ansible.builtin.file:
    path: "/etc/prometheus/certs"
    state: 'directory'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0755'

- name: 'Generate Prometheus client certificate for Nomad metrics.'
  ansible.builtin.shell:
    cmd: |
      {{ step_ca.executable }} \
        ca certificate \
        "prometheus.client.nomad" \
        "/etc/prometheus/certs/nomad-client.crt" \
        "/etc/prometheus/certs/nomad-client.key" \
        --provisioner="{{ step_ca.default_provisioner.name }}" \
        --password-file="{{ step_ca.default_provisioner.password_path }}" \
        --san="prometheus.client.nomad" \
        --san="prometheus" \
        --san="{{ clean_hostname }}" \
        --san="{{ ipv4_address }}" \
        --not-after='24h' \
        --console \
        --force
  notify:
    - 'Restart Prometheus.'

- name: 'Fix permissions on Prometheus client certificates.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'file'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0600'
  loop:
    - "/etc/prometheus/certs/nomad-client.crt"
    - "/etc/prometheus/certs/nomad-client.key"

- name: 'Render default target configs.'
  ansible.builtin.template:
    src: "{{ filename }}.j2"
    dest: "{{ prometheus_config_dir }}/file_sd/{{ filename }}"
  loop:
    - 'node.yaml'
  loop_control:
    loop_var: 'filename'
  notify:
    - 'Restart Prometheus.'

- name: 'Configure Nginx on the load balancer.'
  ansible.builtin.template:
    src: 'nginx-prometheus.conf.j2'
    dest: '/etc/nginx/sites-enabled/prometheus.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  delegate_to: "{{ groups['haproxy'] | first }}"
  run_once: true
  notify:
    - 'Restart Nginx on the load balancer.'

# Consul Service Discovery Registration
- name: 'Register Prometheus with Consul service discovery.'
  ansible.builtin.template:
    src: '../../goldentooth.setup_consul/templates/consul-service-registration.json.j2'
    dest: '/etc/consul.d/prometheus-service.json'
    owner: 'consul'
    group: 'consul'
    mode: '0644'
  vars:
    consul_service_name: prometheus
    consul_service_port: 9090
    consul_service_tags:
      - goldentooth
      - monitoring
      - metrics
      - http
    consul_service_type: monitoring
    consul_service_protocol: http
    consul_service_health_path: /-/healthy
    consul_service_health_http: "http://{{ ipv4_address }}:9090/-/healthy"
  notify:
    - 'Reload Consul configuration.'

- name: 'Add Consul reload handler for Prometheus service registration.'
  ansible.builtin.meta: flush_handlers
