---
- name: 'Render default target configs.'
  ansible.builtin.template:
    src: "{{ filename }}.j2"
    dest: "{{ prometheus_config_dir }}/file_sd/{{ filename }}"
  loop:
    - 'node.yaml'
  loop_control:
    loop_var: 'filename'
  notify:
    - 'Restart Prometheus.'

- name: 'Configure Nginx on the load balancer.'
  ansible.builtin.template:
    src: 'nginx-prometheus.conf.j2'
    dest: '/etc/nginx/sites-enabled/prometheus.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  delegate_to: "{{ groups['load_balancer'][0] }}"
  run_once: true
  notify:
    - 'Restart Nginx on the load balancer.'
