---
# - name: 'Install and configure Prometheus.'
#   ansible.builtin.import_role:
#     name: 'prometheus.prometheus.prometheus'

- name: 'Configure Nginx on the load balancer.'
  ansible.builtin.template:
    src: 'nginx-prometheus.conf.j2'
    dest: '/etc/nginx/sites-enabled/prometheus.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  delegate_to: "{{ groups['load_balancer'][0] }}"
  run_once: true
  notify:
  - 'Restart Nginx on the load balancer.'
