node_homepage.nginx.user: 'www-data'
node_homepage.nginx.group: 'www-data'

# List of dicts defining additionally enabled collectors and their configuration.
# It adds collectors to those enabled by default.
#
# Default:
#   - 'systemd'
#   - textfile:
#       directory": "{{ node_exporter_textfile_dir }}"
node_exporter_enabled_collectors:
  - 'systemd'
  - textfile:
      directory": "{{ node_exporter_textfile_dir }}"
